# Generated by Django 3.1.3 on 2024-05-08 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('curp', models.CharField(max_length=18)),
                ('sexo', models.CharField(max_length=1)),
                ('escuela_procedencia', models.CharField(max_length=100)),
                ('grado_grupo_asignado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('recibo', models.URLField()),
                ('descuento', models.IntegerField(default=0)),
                ('id_recibo', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PadresTutores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_padre_tutor', models.CharField(max_length=100)),
                ('curp_tutor', models.CharField(max_length=18)),
                ('scan_ine', models.URLField()),
                ('telefono', models.CharField(max_length=20)),
                ('scan_comprobante_domicilio', models.URLField()),
                ('email_padre_tutor', models.EmailField(max_length=254)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyenroll.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.BooleanField(default=False)),
                ('tipo_inscripcion', models.CharField(max_length=10)),
                ('modalidad_pago', models.CharField(max_length=2)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyenroll.alumno')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyenroll.pago')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoAlumnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carta_buena_conducta', models.BooleanField(default=False)),
                ('certificado_primaria', models.BooleanField(default=False)),
                ('curp_alumno', models.BooleanField(default=False)),
                ('acta_nacimiento', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('cda', models.URLField(blank=True)),
                ('autorizacion_irse_solo', models.BooleanField(default=False)),
                ('autorizacion_publicitaria', models.BooleanField(default=False)),
                ('atencion_psicologica', models.BooleanField(default=False)),
                ('padecimiento', models.TextField(blank=True)),
                ('uso_aparato_auditivo', models.BooleanField(default=False)),
                ('uso_de_lentes', models.BooleanField(default=False)),
                ('lateralidad', models.CharField(max_length=1)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyenroll.alumno')),
            ],
        ),
    ]
